"""added dailylog dietplan

Revision ID: 6bd5fd931a14
Revises: b7982ff38a6d
Create Date: 2026-06-15 15:55:03.980517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bd5fd931a14'
down_revision: Union[str, Sequence[str], None] = 'b7982ff38a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('water_logged', sa.Integer(), nullable=True),
    sa.Column('steps_logged', sa.Integer(), nullable=True),
    sa.Column('cardio_logged', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('supplement_checkoffs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workout_completed', sa.Boolean(), nullable=True),
    sa.Column('cardio_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diet_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('meals_target', sa.Integer(), nullable=True),
    sa.Column('water_target', sa.Integer(), nullable=True),
    sa.Column('steps_target', sa.Integer(), nullable=True),
    sa.Column('cardio_target', sa.Integer(), nullable=True),
    sa.Column('tolerance_percent', sa.Integer(), nullable=True),
    sa.Column('target_macros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supplement_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id')
    )
    op.drop_table('meal_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('athlete_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('logged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('food_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('raw_vision_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('estimated_calories', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('estimated_protein', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('estimated_carbs', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('estimated_fat', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('estimated_micronutrients', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_edited', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('serving_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], name=op.f('meal_logs_athlete_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('meal_logs_pkey'))
    )
    op.drop_table('diet_plans')
    op.drop_table('daily_logs')
    # ### end Alembic commands ###
