"""added vision table

Revision ID: 96c5fffdf4b1
Revises: b98870456f77
Create Date: 2026-06-12 11:45:47.074448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96c5fffdf4b1'
down_revision: Union[str, Sequence[str], None] = 'b98870456f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vision_api_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('api_provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('meal_logs', 'edited_protein')
    op.drop_column('meal_logs', 'edited_micronutrients')
    op.drop_column('meal_logs', 'edited_fat')
    op.drop_column('meal_logs', 'edited_carbs')
    op.drop_column('meal_logs', 'edited_calories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_logs', sa.Column('edited_calories', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('meal_logs', sa.Column('edited_carbs', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('meal_logs', sa.Column('edited_fat', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('meal_logs', sa.Column('edited_micronutrients', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('meal_logs', sa.Column('edited_protein', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_table('vision_api_calls')
    # ### end Alembic commands ###
