"""add serving size

Revision ID: b7982ff38a6d
Revises: 96c5fffdf4b1
Create Date: 2026-06-12 13:13:16.715844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7982ff38a6d'
down_revision: Union[str, Sequence[str], None] = '96c5fffdf4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_logs', sa.Column('serving_size', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_logs', 'serving_size')
    # ### end Alembic commands ###
